name:           cattleServer
version:        0.11.0

dependencies:
  - aeson
  - aeson-pretty
  - base
  - bytestring
  - directory
  - extra
  - filepath
  - process
  - simplessh
  - text
  - time
  - unix

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  cattleServer:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cattleServer
    when:
    - condition: flag(library-only)
      buildable: false
# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "stack devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
